### ISSUE TITLE
redmine 2.2. and rails 1.9.3 - undefined method `display_tracker_select' 

### ISSUE THREAD

**Issue by cforce** [jijeshmohan/redmine_track_control#12] opened 2013-01-09 10:30 UTC
Wehn i try to open an issue i get this error:

ActionView::Template::Error (undefined method `display_tracker_select' for #<#<Class:0xc8dcf00>:0xc8d9a58>):
    13: <% end %>
    14: 
    15: <% if @issue.safe_attribute? 'tracker_id' %>
    16: <p><%= display_tracker_select(@project,@issue,f)%></p>
    17: <% end %>
    18: 
    19: <% if @issue.safe_attribute? 'subject' %>
  app/helpers/application_helper.rb:996:in`labelled_fields_for'
  app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb___504939791_103497810'
  app/helpers/application_helper.rb:989:in`labelled_form_for'
  app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb___504939791_103497810'
  app/views/issues/show.html.erb:136:in`_app_views_issues_show_html_erb___619203998_95653690'
  app/controllers/issues_controller.rb:119:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:116:in`show'

**Comment by jijeshmohan** [comment] 2013-01-09 11:09
Hi,

I have tested with   Redmine version : 2.2.0.stable  & ruby-1.9.3-p194 and it is working fine in my box. 

May be a conflict with other plugins. Can you please let me know what are the other plugins which you are using along with this one?

**Comment by cforce** [comment] 2013-01-09 11:18
undefined method mnostly is not cross plugin problem, be sure all is commited?

Issue Hot Buttons Plugin plugin
Plugin for Redmine that add buttons for often used actions to issue page
http://thumbtack-technology.github.com/redmine-issue-hot-buttons
Mike Kolganov, Thumbtack Inc.   0.4.4   Konfigurieren
Latest Issues plugin
This plugin will display latest issues on the Redmine Homepage
http://redmine.gogolek.co.uk/projects/redmine-latest-issues
Kasia Gogolek   0.0.1  
Planner
Redmine Resource Planner Plugin
https://github.com/dr-itz/RedminePlannerPlugin
Daniel Ritz 0.4 
Redmine Anonymous Authors plug-in
Allows to specify the author's name and the email for anonymously created issues.
http://redmine.academ.org
Anton Argirov   0.0.3   Konfigurieren
Redmine Anonymous Watchers plug-in
Allows to add emails as watchers and subscribe to Redmine events anonymously
http://redmine.academ.org
Anton Argirov   0.1.0   Konfigurieren
Redmine Automatic Subscription plugin
Subscribes user automatically to issue, news after posting notes to it
http://redmine.academ.org
Anton Argirov   0.0.1  
Redmine Banner plugin
Plugin to show site-wide message, such as maintenacne informations or notifications.
https://github.com/akiko-pusu/redmine_banner
Akiko Takano    0.0.8   Konfigurieren
Redmine Charts
Plugin for Redmine which integrates some nice project charts.
http://github.com/pharmazone/redmine_charts2/
Alexey Mirniy   0.2.1  
Redmine Code Review plugin
This is a Code Review plugin for Redmine
http://www.r-labs.org/projects/show/codereview
Haruyuki Iida   0.6.1  
Redmine CRM plugin
This is a CRM plugin for Redmine that can be used to track contacts and deals information
http://redminecrm.com
RedmineCRM  3.1.0-pro-beta-2    Konfigurieren
Redmine Custom Workflow plugin
Allows to create custom workflows for issues, defined in the plain Ruby language
http://redmine.academ.org
Anton Argirov   0.0.4  
Did You Mean?
A plugin to search for duplicate issues before opening them.
http://www.github.com/abahgat/redmine_didyoumean
Alessandro Bahgat and Mattia Tommasone  1.2.0   Konfigurieren
DMSF
Document Management System Features
https://github.com/danmunn/redmine_dmsf
Vit Jonas / Daniel Munn 1.4.5 stable    Konfigurieren
Redmine Favourite Projects plugin
This is a plugin for Redmine to provide a list of favourite projects on My Page, Top Menu or Project Jumplist
https://github.com/syntacticvexation/redmine_favourite_projects
Syntactic Vexation  0.6.2   Konfigurieren
Posting issues helper API plugin
Add some APIs for helping to post issues via REST API.
https://github.com/opengroove/redmine_fulmo_helper
OpenGroove, Inc.    1.0.0  
Redmine Impasse plugin
Test management tool integrated Redmine
http://unit8.net/redmine_impasse
kawasima    1.2.2   Konfigurieren
Issue Importer
Issue import plugin for Redmine.
Martin Liu / Leo Hourvitz   1.0 
Redmine Incoming Mail Log plugin
A plugin to record incoming mails and statuses of handling them.
http://github.com/commandprompt/redmine_incoming_mail_log
Alex Shulgin ash@commandprompt.com    0.2.0   Konfigurieren
Redmine Attach Screenshot plugin
Attach screenshots from clipboard directly to a Redmine issue.
https://bitbucket.org/StrangeWill/redmine-inline-attach-screenshot/
Konstantin Zaitsev, Sergei Vasiliev, Alexandr Poplavsky, Axmor Software, Jens Alfke, Renzo Meister, William Roush   0.4.2  
Redmine Issue History Tabs plugin
This plugin provide history of issue in tabs representation
Daniel MunnKonstantin Zaitsev   0.0.3  
Redmine Issue Templates plugin
Plugin to generate and use issue templates for each project to assist issue creation.
https://bitbucket.org/akiko_pusu/redmine_issue_templates
Akiko Takano    0.0.5  
Redmine Issues Poll
This is a plugin for Redmine to elect issues
https://github.com/dextra/redmine_issues_poll
Dextra Sistemas 0.1.0  
Redmine - Ldap Sync
Syncs users and groups with ldap
https://github.com/thorin/redmine_ldap_sync
Ricardo Santos  1.3.0   Konfigurieren
Redmine Local Avatars plugin
This plugin lets users upload avatars directly into Redmine
Andrew Chaika and Luca Pireddu  0.1.1  
Meetings plugin
plugin to manage meetings in REDMINE
Arnaud Martel   0.2.3   Konfigurieren
Redmine Milestones plugin
Create, edit and manage milestones
http://redminecrm.com/projects/milestones
RedmineCRM  1.0.0-pro-alpha1  
Redmine (Monitoring & Controlling | Monitoramento & Controle)
Este plugin foi criado para auxiliar no Monitoramento e Controle dos projetos no redmine através de uma visualização gráfica das tarefas e sua execução. This plugin is a graphic tool to Monitoring and Controlling projects on redmine.
http://alexmonteiro.github.com/redmine_monitoring_controlling/
Alexander Monteiro  0.1.1  
Mylyn Connector plugin
This plugin provides a webservice API for Eclipse Mylyn (RESTful)
Sven Krzyzak / Daniel Munn  2.8.2.stable  
Redmine Newissuealerts plugin
Send an email to a list of addresses when a new issue is created
http://redmine.debuntu.org/projects/redmine-newissuealerts
Emmanuel Bretelle   0.0.2  
Redmine PDF Documents plugin
Erzeugung von PDF Dokumenten aus mehreren Wiki Seiten
https://github.com/klausmeyer/redmine_pdf_documents_documents
Klaus Meyer 0.0.1  
Redmine People plugin
This is a plugin for managing Redmine users
http://redminecrm.com/projects/people
RedmineCRM  0.0.2  
Redmine plugin views revisions plugin
This plugin tries to solve problem that is caused by inability to monkey-patch views in the Redmine. For details please see http://www.redmine.org/plugins/redmine_plugin_views_revisions for more details
Vitaly Klimov   0.0.1  
Private Wiki
Adds private pages to wiki
Oleg Kandaurov  0.2.1  
Redmine Spent Time plugin
Redmine's plugin to show and load projects' spent time
Eduardo Yáñez Parareda    2.4.0  
Redmine Textilizable Custom Fields plug-in
Adds textilizable support to text and long text custom fields
http://redmine.academ.org
Anton Argirov   0.0.1  
Redmine Time Tracker plugin
This is a plugin to track time in Redmine
Christian Reich 0.6 Konfigurieren
Redmine Wiki Extensions plugin
This is a Wiki Extensions plugin for Redmine
http://www.r-labs.org/projects/r-labs/wiki/Wiki_Extensions_en
Haruyuki Iida   0.6.1  
Redmine Wiki Lists plugin
wiki macros to display lists of contents.
https://bitbucket.org/kusu/redmine_wiki_lists
Tomohisa Kusukawa   0.0.1  
Issues XLS export
Export issues to XLS files including journals, descriptions, etc. This plugin requires spreadsheet gem.
Vitaly Klimov   0.2.1   Konfigurieren
Scrum2B Plugin
A scrum tool for team to work: - Scrum board - Customize views
https://github.com/scrum2b/scrum2b
Scrum2B 0.1 Konfigurieren
Sidebar Hide Plugin
This plugin provides ability to hide sidebar
http://www.redmine.org/projects/redmine/wiki/Plugin_Tutorial
Furkan Yavuz    0.0.1  
Redmine System Notification plugin
The System Notification plugin allows Administrators to send systemwide email notifications to specific users.
https://github.com/ande3577/redmine-system-notification-plugin
David S Anderson    0.3.0  
Timelog Timer plugin
A simple javascript timer for Hours field in timelog form
https://github.com/behigh/redmine_timelog_timer.git
Behigh  2.0.0  
Wiki user macros
Macros to display list of users and project members.
http://github.com/alexandermeindl/wiki_user_macros

**Comment by jijeshmohan** [comment] 2013-01-09 11:51
I have checked this by cloning this repo, so very sure this is not a pblm with uncommitted file :) . You can even check the code in your plugin directory redmine_track_control/lib/issue_helper_patch.rb

It will take some time to reproduce due to the number of plugins you are using.

**Comment by hitzel** [comment] 2013-01-11 14:39
Same problem here. I used the following plugins
- redmine_close_button
- redmine_contacts
- redmine_contacts_helpdesk
- redmine_default_assign
- redmine_didyoumean
- redmine_inline_attach_screenshot
- redmine_issue_checklist
- redmine_ldap_sync
- redmine_people
- redmine_questions

**Comment by cforce** [comment] 2013-01-16 12:55
Her we use:
redmine_contacts
redmine_contacts_helpdesk
redmine_didyoumean
redmine_inline_attach_screenshot
redmine_issue_checklist
redmine_ldap_sync
redmine_people

**Comment by Cissi** [comment] 2013-01-21 13:05
The permissions is not possible to set in RM 2.2.1

See my environment
Environment:
  Redmine version                          2.2.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.11
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_backlogs                         v0.9.32
  redmine_checkout                         0.6-BETA
  redmine_ldap_sync                        1.3.0
  redmine_track_control                    1.0.6
  redmine_wktime                           1.0

Every time I try to add a permission to a certain tracker it is not updated in the settings and I cannot use the tracker.
So please see that the settings of permissions is working as it should...

BR Cecilia

**Comment by Cissi** [comment] 2013-01-22 04:08
Anyone succeeded to save tracker permissions for tracker with a space in the name?

**Comment by cforce** [comment] 2013-01-22 09:26
Nope.

**Comment by cforce** [comment] 2013-02-13 09:03
Btw. i still have the bug "undefined method `display_tracker_select'"

**Comment by Cissi** [comment] 2013-02-13 10:40
We have succeed to use the plugin with the following settings:

Environment:
  Redmine version                          2.2.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.11
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_backlogs                         v0.9.32
  redmine_checkout                         0.6-BETA
  redmine_ldap_sync                        1.3.0
  redmine_track_control                    1.0.6
  redmine_wktime                           1.3

Once the latest patch was integrated it worked.
I do not get the undefined method as far as I know.

Best Regards
Cecilia

**Comment by cforce** [comment] 2013-02-13 12:08
I have the latest patch on redmine2 branch too, maybe its a cros plugin problem, and i am not alone, see  @hitzel hitzel

**Comment by markedagain** [comment] 2013-02-27 06:18
ok i can confirm that uninstalling advanced roadmaps fixes this issue. im no expert, but i think the lib's have to be in a namespace. i tried moving it myself, but cant figure it out for the life of me.

i can also confirm when i remove this from advance roadmaps #IssuesController.send(:include, AdvancedRoadmap::IssuesControllerPatch) it fixes the issue.

**Comment by dipanm** [comment] 2013-04-17 06:43
I have faced the same issue. 

However, I am NOT using the  "advanced roadmaps" plugin as described above. Rather the issue is found when I am using "Redmine Release notes" plugin : https://github.com/hdgarrood/redmine_release_notes using latest version 1.3.1 - I have confirmed that either of the plugin works independently fine - but together they do not work.

So I may conclude that different plugins - perhaps any other plugin would face the same trouble if the Issue or Issue controller is patched.

**Comment by markedagain** [comment] 2013-04-17 16:37
yup i also had to comment out some features. 
the main issue is this plugin does not use a hook to change the select box, it replaces the entire issue layout. so if another plugin was also trying to replace the issue layout then we get a conflict of plugins trying to overwrite. as i am not very good in rubyt my only solution has been to comment out the issue template on the other plugins i use basue tracker pemisions is important to us

**Comment by dipanm** [comment] 2013-04-17 18:45
I am not sure if there is any alternative hook way of implementing only one field per say. Yes, the layout is partially re-written. But the error we are getting is when the InstanceMethods (specifically display_tracker_select) which should get attached to issue class - but won't get there. 

In fact I tried one more _funny_ stuff. Assuming that redmine will initialize plugins in some set (alphabetical) order - and the fact that both advanced_roadmap and redmine_release_notes come above redmine_track_control - I tried to rename the tracker_control plugin - to control_tracker. Surprisingly - now issue page and new-issue page are no longer breaking! BUT - the tracker should get filtered out are NO LONGER filtering. BTW - its not that the plugin has bee discarded - it still have all checkboxes in permission page and project setting page! 

But I really don't know what is wrong in here...

**Comment by jijeshmohan** [comment] 2013-04-18 04:23
In this plugin, it is not possible without replacing entire issue layout. But I am trying to avoid the conflict issue by wrapping the plugin code into another module. Will update the same if it worked. Hopefully I will be able to finish it by this weekend.

**Comment by dipanm** [comment] 2013-04-18 04:47
Thanks, @jijeshmohan  - will wait eagerly. BTW - this is very useful plugin. Thanks a lot.

**Closed as completed** 2013-04-21 10:11 UTC

**Comment by jijeshmohan** [comment] 2013-04-21 10:14
I have modified the code to fix this bug. I have tested with https://github.com/hdgarrood/redmine_release_notes and now it is working fine. Please try with latest code and let me know.

**Comment by dipanm** [comment] 2013-04-21 12:03
Wow ! Will quickly try this out. It would be a great help. Thanks a lot.

**Comment by dipanm** [comment] 2013-04-29 05:31
That's very cool!!  The plugins are now working together very well! Thanks a ton.

BTW: I have filed another bug - take a look.
