### ISSUE TITLE
tracker permissions does not save! 

### ISSUE THREAD

**Issue by atopcu** [jijeshmohan/redmine_track_control#8] opened 2012-10-23 18:28 UTC
Dear jijeshmohan,

There are two case in this plugin. Tracker permissions does not save in Administration page;
1. when the tracker name is more than one word (SW Support, HW Support etc.)
2. when the tracker name contain non english characters. 

Environment:
  Redmine version: 2.1.2.stable
  Ruby version: 1.8.7 (x86_64-linux)
  Rails version: 3.2.8
  Environment: production
  Database adapter: MySQL

Note: I do not see Second Case in version 1.0.1 in redmine 1.3.2, but first case was exist it too.

Best Regards,

**Comment by jijeshmohan** [comment] 2012-10-24 04:06
The second defect is there with 2.1.x version due to the change in the redmine core code. This will work fine in the lower version .

**Comment by atopcu** [comment] 2012-10-24 10:06
Yes, you're right!

**Comment by cforce** [comment] 2012-12-10 23:24
Is it fixed now?

**Comment by jijeshmohan** [comment] 2012-12-28 12:25
New build will work with spaces in the tracker name. unicode yet to fix

**Comment by Cissi** [comment] 2013-01-21 13:06
which build should I use, maybe this will solve my problem...

**Comment by jijeshmohan** [comment] 2013-01-21 14:37
Please download : https://github.com/jijeshmohan/redmine_track_control/archive/redmine2.zip

This fixed only space problem not the unicode one. I have tested it in 2.2 stable version and it worked.

**Comment by Cissi** [comment] 2013-01-22 04:04
We used the above link to update the plugin and still the bug is there.. I will see if we can get a error message from a log today.,

**Comment by jijeshmohan** [comment] 2013-01-22 04:29
It will be great if you can send me the error log. I am unable to reproduce this.

**Comment by Cissi** [comment] 2013-01-22 04:38
I will see What We Can Do..

Sent from my HTC

----- Reply message -----

**Comment by Cissi** [comment] 2013-01-22 08:38
Hello

We have installed Redmine 2.2.1 and tracker control the same version that we use, created a new tracker containing a name with a space, and here we can save the permissions, but in our database where the tracker is already existing in it and then update the plugin it still not work, that is you cannot save new settings for an old tracker created earlier.

I tried to work around it by simply adding a new tracker and try to change all old issues to the new tracker but it did not work, and when I tried to remove the new tracker your plugin still remember the new tracker that is deleted.

![trackers in the system](https://f.cloud.github.com/assets/1712259/85569/500599dc-6469-11e2-92c1-d88879e94d78.jpg)
![tracker permissions not updated](https://f.cloud.github.com/assets/1712259/85570/54ce07e2-6469-11e2-8417-69576826efb1.jpg)

In the first picture you see which trackers I have and in the second image you see that your plugin remembers even the deleted tracker.

I think you should be able to recreate the problem by following the following steps
1. Create a Redmine instance with RM2.0.4 and tracker control 1.0
2. Add a tracker with a name with a space in it like change request
3. Add a project with it activated both the module and the tracker and for which role it should be visable for
4. Add a member in the project with permissions to add the trackertype
5. Create at least one and two issues of the tracker change request with some data in it
6. Upgrade now that instance to RM2.2.1 and tracker control to your latest commit
7. Now you will see that it does not remember any permissions for your plugin for any roles
8. Try to add permissions for all roles and then press save 
9. It says the update is done sucessful
10. Check the permissions, all trackers with a name without a space the permissions are saved but not for the tracker with a name whith a space in it

So two questions arise, why is not the earlier permissions saved when upgrading and two the space problem is not solved for databases containing old data.

We will continue to try to find the problem from our side as well, we suspect that it write and read data from two places.

BR Cecilia Dahlgren

**Comment by jijeshmohan** [comment] 2013-01-22 08:52
Looks like a problem with the earlier data ( which may be corrupted as well) . Could you please add a new tracker with space in the upgraded instance and try to set permission for that one?

**Comment by Cissi** [comment] 2013-01-22 09:09
That We can Do, but not delete the Old One and rename it...

Sent from my HTC

----- Reply message -----

**Comment by Cissi** [comment] 2013-01-23 08:00
Remember that I created a new instance with a totally new empty database, I then we added only your plugin, created a new tracker with a name that has a space, once I saved it everything seams fine, but today when I go into the same instance with no old data the permissions are gone again.

Something is wrong...  I also tried what you suggested above, but that do not worked either. Everything seems fine at the beginning but then the problem come back.. 

Please see if you can reproduce the problem in below environment
Environment:
  Redmine version                          2.2.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.11
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_backlogs                         v0.9.32
  redmine_checkout                         0.6-BETA
  redmine_ldap_sync                        1.3.0
  redmine_track_control                    1.0.6
  redmine_wktime                           1.3

I really love your plugin, and I don´t think it is corrupted data since all other trackers are working fine and no upgrade problem at all... All trackers have been created at the same time in production so why should the corruption of data only appear in trackers with a space in the tracker name...

Best Regards
Cecilia Dahlgren

**Comment by Cissi** [comment] 2013-01-23 08:03
Hm, maybe the other plugins interfere, but what should my developers look for...

**Comment by jijeshmohan** [comment] 2013-01-23 08:09
Humm this new issue might be a big problem, i was able to reproduce the older data problem, which is basically corrupted the tracker permission ( not anything other than the tracker which has space, it won't affect anything else ) due to the incompatibility with that version.  
For this issue I thought of creating an admin page where you can just re-create the permission for each tracker. 

But the above issue which you reported have to evaluate more . It should not affect new tracker which created after the migration.

**Comment by Cissi** [comment] 2013-01-23 08:22
But I am not sure that is the case since after the test we added the other plugins, it might have affected something, but now issues are created. 

I will try to rename the names to something without a space and see what happens, but I am not so hopeful since when I later will try to rename the tracker with space again I think the problem will come back.

Thanks for trying to help me though...

Are you working in a production daily with trackers that have a space in it?

But I did create a new tracker moved all old tracker data into the new tracker and then removed the old tracker and everything seamed well, but once I tried to rename it back to the old name the problem was there again,

Please let me know if you would like me to try something else.

BR Cecilia

**Comment by Cissi** [comment] 2013-01-23 08:25
I tried to just rename the tracker to a name without a space, that did not solve the problem at all, the new trackername do not appear in the window either. Maybe I need to restart the database though.

Next I will try is to create a totally new tracker name without space and then move all issues to that one and then try to rename it to something with a space...

I let you know when I have tried that.

BR Cecilia

**Comment by Cissi** [comment] 2013-01-23 08:29
Hm, the new tracker I create does not appear any longer at all in the list of your plugin settings under roles and permissions, I guess my earlier trials have destroyed the data totally. What shall I do?

**Comment by Cissi** [comment] 2013-01-23 08:46
Seams like rename them to a tracker name without a space solves the problem to make them visable again for the developer, but I cannot see the new tracker permission in the table so I did not know it was actually working until I tried to create one new issue. 

The question is what will happen when I change back to a name with a space will the problem reappear, and what about the permissions I cannot longer see what permissions I have.

**Comment by rsilvestri** [comment] 2013-01-24 07:46
Hi all,
just came accross this and in fact I faced the same problem. There is a simple fix for this by applying below patch. It would be great to get this fixed in the repository as well:

From f7a8aea4f6ab17b43e08d8deb11df88720cd461c Mon Sep 17 00:00:00 2001
From: Ruedi Silvestri ruedi.silvestri@silvtec.com
Date: Thu, 24 Jan 2013 08:36:12 +0100
Subject: [PATCH] Ensure correct creation of Permission handling blanks
 correctly.

---

 init.rb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/init.rb b/init.rb
index 0e4aff4..d62bb2c 100644
--- a/init.rb
+++ b/init.rb
@@ -24,7 +24,7 @@ Redmine::Plugin.register :redmine_track_control do

   project_module :tracker_permissions do
     Tracker.all.each do |t|
-      permission "create_#{t.name.downcase}_tracker".to_sym, {:issues => :index}
-      permission "create_#{t.name.downcase.gsub(/\ +/,'_')}_tracker".to_sym, {:issues => :index}
   end
  end
  end
  -- 
  1.8.0.msysgit.0

**Comment by cforce** [comment] 2013-01-24 08:38
Please merge into repo soon!

**Comment by jijeshmohan** [comment] 2013-01-24 09:03
Done.

**Comment by Cissi** [comment] 2013-01-25 05:18
Hello... I have installed the new commit and everything is working as it should now, thanks a lot @Ruedi Silvestri
you saved our company a lot of headache. Thanks a lot for merging so quick, @jijeshmohan  now the upgrade to RM 2,2,X is almost secured.

Thanks a lot.

BR Cecilia Dahlgren

**Comment by Cissi** [comment] 2013-02-13 10:42
Hello, as far as I am concerned this issue can be closed.

**Comment by markedagain** [comment] 2013-03-06 19:49
i had a tracker called request i changed it to request / changes .
this cause the permissions to get lost, then i could not save it. looking at the db there was "" wrapped around that tracker name.

now when i try to rename or do anything that tracker is lost and cant have any changes made to it

**Closed as completed** 2013-05-01 06:33 UTC
